### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by glensc** [glensc/PlexTraktSync#32]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

1

### Expected behavior

1

### Steps to reproduce the behavior

1

### Install method

pipx

### Config file

```yaml
cache:
  path: /Users/glen/.cache/PlexTraktSync/trakt_cache
config:
  dotenv_override: true
excluded-libraries:
- Kristīnei
- Family Holidays
logging:
  append: true
  console_time: false
  debug: true
  filename: /Users/glen/Library/Logs/PlexTraktSync/plextraktsync.log
  filter:
  - level: WARNING
    message: not found on Trakt
  - level: WARNING
    message: because provider local has no external Id
  - level: WARNING
    message: because provider none has no external Id
  - level: WARNING
    message: Retry using search for specific Plex Episode
plex:
  timeout: 30
sync:
  plex_to_trakt:
    collection: true
    ratings: false
    watched_status: true
    watchlist: false
  skip_label: skip-pts
  trakt_to_plex:
    liked_lists: true
    ratings: false
    watched_status: true
    watchlist: false
    watchlist_as_playlist: false
watch:
  add_collection: true
  remove_collection: false
  scrobble_threshold: 800
  username_filter: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.23.0dev0

### Python Version

3.10.8

### Operating System and Version

macOS-10.15.7
